version: '3.5'

services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   container_name: postgres
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3333
    ports:
      - '3333:3333'
    # depends_on:
    #   - db
    env_file:
      - .env
    volumes:
      - ./src:/backend/src
      - ../backend:/backend
